"""add_gestores_client_nf_fields

Revision ID: 99dfed16abe6
Revises: 
Create Date: 2026-05-27 14:51:59.771599
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '99dfed16abe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestores_id'), 'gestores', ['id'], unique=False)
    op.add_column('clients', sa.Column('cpf_cnpj', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('email', sa.String(length=180), nullable=True))
    op.add_column('clients', sa.Column('cep', sa.String(length=9), nullable=True))
    op.add_column('clients', sa.Column('endereco', sa.String(length=300), nullable=True))
    op.add_column('clients', sa.Column('cidade', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('estado', sa.String(length=2), nullable=True))
    op.add_column('service_orders', sa.Column('gestor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_orders', 'gestores', ['gestor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_orders', type_='foreignkey')
    op.drop_column('service_orders', 'gestor_id')
    op.drop_column('clients', 'estado')
    op.drop_column('clients', 'cidade')
    op.drop_column('clients', 'endereco')
    op.drop_column('clients', 'cep')
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'cpf_cnpj')
    op.drop_index(op.f('ix_gestores_id'), table_name='gestores')
    op.drop_table('gestores')
    # ### end Alembic commands ###
